### PR TITLE
Add Shielded Uranium, Graphene

### PR DESCRIPTION
**Pull request by Eb-**
# **Shielded Uranium**
 * A less radioactive material for handling uranium "safely"
 * Still emits radiation, just hurts less.
 * Can not go supercritical and explode
 * not as useful with radiation collectors
 * 10% Uranium / 10% Steel / 80% Carbon (makes the Graphene)
 * Appraisal Value
  * Uranium worth 90% of "pure" value per KG
  * Steel worth 100% of Steel value per KG
  * Carbon worth 100% of Graphene value per KG

 # **Graphene Sheets**
 * A use for Carbon, which often piles up unused in mining stations
 * Takes a little longer to process (2x as long as Steel)
 * Same value as Steel

### CODE REVIEW

**Comment by Partmedia** [comment]
Thank you for your contribution.

1. You say:

    > Inside of the mining gamemode, uranium can not be stacked.
    
    But with the stack component that was re-added, they can indeed stack again in the mining game mode:
    
    image
    
    Ditto for shielded uranium.
    
2. Despite graphene having an "Extractable" component, it is nevertheless still not grindable in the grinder.
    image

3. Case issue in YAML leading to the shielded uranium producing no radiation. I can fix that.

4. You say:

    > Some bits of the existing Uranium definition were not written to account for CaseSensitive systems. For example, was unable to run on my Linux system. This has been fixed.

    SS14 YAML should actually be case-sensitive on all systems. I also develop on Unix :) According to the diff, the only case adjustments were to the shielded uranium prototypes that were added.

**Comment by Partmedia** [comment]
Unless you want to take another look, I propose removing the stack components again. I can correct the case issues. If you would be able to investigate the grindability of graphene, that would be wonderful.

**Comment by Eb-** [comment]
i got caught up pretty late working on this, looks like i missed a lot of little things from that, oops! Feel free to address the casing issues, i'll take a look at the graphene grindability and removing the stack components.

re: the casing issues, that only leaves user error on my end! I must of accidentally made most things lowercase in my duplication of Uranium, ahah

**Comment by Eb-** [comment]
turns out it was another casing error! both Graphene and Shielded Uranium are now grindable.

I am also considering tweaking the ratio of Uranium / Steel / Carbon in Shielded Uranium for gameplay purposes, but I think it would be best to witness it in play more before that.

**Comment by Partmedia** [comment]
I fixed a few more casing errors. Most of these should be caught by the YAML Linter. You can run that through your IDE or through this project's convenient `make lint` target.

**Comment by Partmedia** [comment]
Even YAML is an adventure, bear with me:

- It looks like you accidentally made the full stack of graphene 'noSpawn', but since graphene can stack I've allowed spawning it.

- It takes 6 coal to make 1 graphene stack. Each coal has 30u of grindable carbon = 180u grindable carbon. However, grinding a full stack of graphene yields 300u carbon:
    
    image

    I have adjusted the graphene reagent quantity to not produce extra carbon.

- Why do the material contents of `SheetShieldedUranium` disagree with its lathe recipe?

**Comment by Eb-** [comment]
> I have adjusted the graphene reagent quantity to not produce extra carbon.

good catch, thank you!

> Why do the material contents of SheetShieldedUranium disagree with its lathe recipe?

i was following the pattern of Uranium:

Uranium's recipe has it consume [500 Uranium](https://github.com/Partmedia/mining-station-14/blob/e2a672f28168fb17449c4207d862426a16a28cc1/Resources/Prototypes/Recipes/Lathes/sheet.yml#L77), and outputs 1 sheet with a material content of [100 Uranium](https://github.com/Partmedia/mining-station-14/blob/e2a672f28168fb17449c4207d862426a16a28cc1/Resources/Prototypes/Entities/Objects/Materials/Sheets/other.yml#LL155C19-L155C19)

i based my calculation entirely off of Uranium, assuming that the reduction of mass after crafting was to address efficiency upgrades to the Ore Processor to prevent some form of infinite resource gain

looking through material quantities once more, i now see that for other recipes the materials used for the recipe vs the material amount in the stack are identical

regarding the material contents of `SheetShieldedUranium` what's the correct course of action here? 
* keep all non-uranium materials equal to their inputs, reduce Uranium mass as per the `SheetUranium` recipe?
* match all material quantities to their recipe masses?
* something else?

**Comment by Partmedia** [comment]
Since it agrees with uranium, I vote do nothing until someone complains. We can fix this if it actually becomes a problem; I don't see too many people grinding uranium. Thank you for your contribution :D

**Comment by Eb-** [comment]
and thanks for being patient with a neophyte! :tada: 

eager to see the changes in play!

**Pull request merged**
